site_name: MCP Security Analysis
repo_url: https://github.com/eilonc-dev/mcp-security-analysis
repo_name: eilonc-dev/mcp-security-analysis

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  palette: 
    - scheme: default 
      primary: blue grey 
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - navigation.instant
    - header.autohide
    - toc.integrate
    - navigation.expand
    - content.code.copy
    - search.suggest

extra_css:
  - assets/css/custom.css

nav:
  - Overview:
    - Home: index.md
    - Core Concepts: 02-core-concepts.md
  - Protocol Deep Dive:
    - Protocol Interactions: 03-protocol-interactions.md
    - Data Structures: 04-data-structures.md
    - Communication Patterns: 05-communication-patterns.md
    - Trust Boundaries: 06-trust-boundaries.md
  - Security Analysis:
    - Component Considerations: 07-security-considerations-per-component.md
    - Threat Modeling (STRIDE): 08-stride-modeling.md
    - Attack Scenarios: 09-attack-scenarios.md
  - Conclusion:
    - Implementation Insights: 10-implementation-insights.md
    - Summary & Hotspots: 11-summary-hotspots.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3